### ISSUE TITLE
compile but not working 

### ISSUE THREAD

**Issue by Shmuel930** [NicoHood/IRLremote#12]
Hi i'm trying to use IRLremote example Receive_Custom, i have arduino uno and I install the HL2

the code is compile with the arduino but i connect my IR receiver and i cant see anything at the serial monitor.

any help?

**Comment by NicoHood** [comment]
Please use the dev2 branch as i am only developing on this. Then you need to use the 16u2 pins. I guess you used the 328 pins. You need to use those on the 16u2 isp header or the 4 pin header which isnt soldered by default. See the hoodloader2 wiki for more information.

Contact me via tox for further support, as this is no real bug.
