### ISSUE TITLE
Use IRLremote with attiny85

### ISSUE THREAD

**Issue by TBeast14** [NicoHood/IRLremote#24]
Well, I'm trying to make a simple project with an attiny85. My idea is turn on and turn off a diode with a TV control and a ir receiver, using attiny85. I don't know how to receive the control code, and use it for turn on or turn off the diode.

**Comment by NicoHood** [comment]
Sorry this is no support Forum. Please ask in the arduino forum or irc chat. If you want to use this library with an attiny you also need the pinchangeinterrupt library.
