### ISSUE TITLE
IRLremote is undefined

### ISSUE THREAD

**Issue by naurisgrinbergs0** [NicoHood/IRLremote#33]
All headers included, but still throws error "IRLremote is undefined"
------------------------------------------------------------------------------------
`
#include <IRL_Time.h>
#include <IRL_Receive.h>
#include <IRL_Protocol.h>
#include <IRL_Platform.h>
#include <IRL_Panasonic.h>
#include <IRL_NecAPI.h>
#include <IRL_Nec.h>
#include <IRL_Keycodes.h>
#include <IRL_Hash.h>
#include <IRL_Decode.h>
#include <IRLremote.h>

void setup()
{
    if (!**IRLremote**.begin(IR_RECV_PIN))
		Serial.println(F("You did not choose a valid pin."));
}

void loop(){
    ...
}
`

**Comment by NicoHood** [comment]
Look at the example. Including all headers does not help in any way:
https://github.com/NicoHood/IRLremote/blob/master/examples/Receive/Receive.ino
